Indexbranch
Interhacks-2020/Simpact pull request #23
Opened 2020-07-03 14:36 UTC by ankoanju

2020-07-03 17:18 UTC, mykyta-protsenko requested changes
It looks good except the duplicate app files. Please select which copy do we need to leave in place, then you should be good to go.

2020-07-03 17:18 UTC, mykyta-protsenko commented on SimpactApp/admin.py
> +from django.contrib import admin
I've noticed that both you and @anavianm created a barebones Django app - but in different folders (you used "SimpactApp" whike @anavianm used "simpact"). I suggest choosing and leaving one.

2020-07-03 19:00 UTC, mykyta-protsenko commented on SimpactApp/admin.py
> +from django.contrib import admin
Or did I get it wrong and you need both folders? Then maybe they can be renamed for clarity?

2020-07-04 00:06 UTC, anavianm approved these changes

2020-07-04 00:59 UTC, merged